# Module-scoped canonical list — both completers read this directly so a single edit keeps
# Get-InforcerReportType and Invoke-InforcerReport completion identical.
# Empirically matched to the production catalog observed against api.inforcer.com.
$script:InforcerReportTypeStaticKeys = @(
    'ActiveUserCount'
    'ActiveUsers'
    'Assessment'
    'CopilotAdoption'
    'CredentialUserRegistrationDetails'
    'EncryptionDisabledDevices'
    'EncryptionEnabledDevices'
    'GetDetectedRisks'
    'GetDetectedServicePrincipalRisks'
    'GetOneDriveUsageAccountCounts'
    'GetOneDriveUsageStorage'
    'GetRiskyServicePrincipals'
    'GetRiskyUsers'
    'GetSharePointSiteUsageDetail'
    'GetSharePointSiteUsageStorage'
    'GetTenantMFAReport'
    'GlobalAdmins'
    'NonCompliantDevices'
    'SecureScores'
    'SecureScoresAverageComparativeScores'
    'SecureScoresControlScores'
    'ShadowAiDetection'
    'SubscribedSkus'
    'TenantAuditReport'
    'TenantMfaReport'
)
